//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationServer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICalculatingService")]
    public interface ICalculatingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnect/Connect", ReplyAction="http://tempuri.org/IConnect/ConnectResponse")]
        string[] Connect(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnect/Connect", ReplyAction="http://tempuri.org/IConnect/ConnectResponse")]
        System.Threading.Tasks.Task<string[]> ConnectAsync(string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatingService/CalculateLine", ReplyAction="http://tempuri.org/ICalculatingService/CalculateLineResponse")]
        int CalculateLine(Shared.CalculateLineData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatingService/CalculateLine", ReplyAction="http://tempuri.org/ICalculatingService/CalculateLineResponse")]
        System.Threading.Tasks.Task<int> CalculateLineAsync(Shared.CalculateLineData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatingServiceChannel : CalculationServer.ServiceReference1.ICalculatingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatingServiceClient : System.ServiceModel.ClientBase<CalculationServer.ServiceReference1.ICalculatingService>, CalculationServer.ServiceReference1.ICalculatingService {
        
        public CalculatingServiceClient() {
        }
        
        public CalculatingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Connect(string[] data) {
            return base.Channel.Connect(data);
        }
        
        public System.Threading.Tasks.Task<string[]> ConnectAsync(string[] data) {
            return base.Channel.ConnectAsync(data);
        }
        
        public int CalculateLine(Shared.CalculateLineData data) {
            return base.Channel.CalculateLine(data);
        }
        
        public System.Threading.Tasks.Task<int> CalculateLineAsync(Shared.CalculateLineData data) {
            return base.Channel.CalculateLineAsync(data);
        }
    }
}
